---
namespace: grafana
name: grafana
version: 5.7.0
readme: README.md
authors:
  - Grafana Labs <grafana.com>
  - Ishan Jain <ishan.jain@grafana.com>
  - Gerard van Engelen <g.vanengelen@codepeople.nl>
description: Ansible collection to manage Grafana resources
license:
  - GPL-3.0-or-later
tags: [grafana, observability, monitoring]
repository: https://github.com/grafana/grafana-ansible-collection
issues: https://github.com/grafana/grafana-ansible-collection/issues
documentation: https://docs.ansible.com/ansible/latest/collections/grafana/grafana/index.html
