---
- name: Converge
  hosts: all
  vars:
    promtail_scrape_configs:
      - job_name: test
        static_configs:
          - targets:
              - localhost
            labels:
              job: test
              instance: "{{ ansible_facts['fqdn'] }}"
              __path__: /var/log/last*
  roles:
    - role: grafana.grafana.promtail
