---
- name: Converge
  hosts: all
  become: true
  tasks:
    - name: Include pyroscope role with S3 backend
      ansible.builtin.include_role:
        name: pyroscope
      vars:
        pyroscope_config_overrides:
          server:
            http_listen_port: 4040
            log_level: debug
          storage:
            backend: s3
            s3:
              bucket_name: pyroscope-test
              endpoint: s3.amazonaws.com
              region: us-east-1
              access_key_id: test_access_key
              secret_access_key: test_secret_key
          multitenancy_enabled: true
          memberlist:
            bind_port: 7946
            join_members:
              - localhost
          limits:
            max_global_series_per_user: 1000000
            ingestion_rate: 50000
            ingestion_burst_size: 100000
        pyroscope_environment_variables:
          GOGC: "100"
          GOMAXPROCS: "4"