---
# tasks file for Tempo deployment
- name: Obtain the latest version from the Tempo GitHub repo
  when: tempo_version == "latest"
  block:
    - name: Scrape Github API endpoint to obtain latest Tempo version
      ansible.builtin.uri:
        url: "https://api.github.com/repos/grafana/tempo/releases/latest"
        method: GET
        body_format: json
      become: false
      delegate_to: localhost
      run_once: true
      register: __github_latest_version

    - name: Latest available Tempo version
      ansible.builtin.set_fact:
        tempo_version: "{{ __github_latest_version.json.tag_name | regex_replace('^v?(\\d+\\.\\d+\\.\\d+)$', '\\1') }}"

- name: Verify current deployed version
  block:
    - name: Check if Tempo binary is present
      ansible.builtin.stat:
        path: "/usr/bin/tempo"
      register: __already_deployed

    - name: Obtain current deployed Tempo version
      ansible.builtin.command:
        cmd: "/usr/bin/tempo --version"
      changed_when: false
      register: __current_deployed_version
      when: __already_deployed.stat.exists | bool

- name: Include RedHat/Rocky setup
  ansible.builtin.include_tasks:
    file: setup-Redhat.yml
  when: ansible_facts['os_family'] in ['RedHat', 'Rocky']

- name: Include Debian/Ubuntu setup
  ansible.builtin.include_tasks:
    file: setup-Debian.yml
  when: ansible_facts['os_family'] == 'Debian'

- name: Check if Tempo default dir is present
  ansible.builtin.stat:
    path: "/tmp/tempo/boltdb-shipper-active"
  register: __default_structure

- name: Default structure cleanup
  when: __default_structure.stat.exists | bool
  block:
    - name: Ensure that Tempo is stopped before default cleanup
      ansible.builtin.systemd:
        name: tempo.service
        state: stopped

    - name: Remove default configuration from "/tmp/tempo" directory
      ansible.builtin.file:
        path: "/tmp/tempo"
        state: absent

- name: Ensure that Tempo working path exists
  ansible.builtin.file:
    path: "{{ tempo_working_path }}"
    state: directory
    owner: "tempo"
    group: "root"
    mode: "0755"

- name: Template Tempo config - /etc/tempo/config.yml
  ansible.builtin.template:
    src: "config.yml.j2"
    dest: "/etc/tempo/config.yml"
    owner: "tempo"
    group: "root"
    mode: "0644"
    validate: "/usr/bin/tempo -config.verify %s"
  notify: Restart tempo

- name: Ensure restart has completed
  ansible.builtin.meta: flush_handlers

- name: Ensure that Tempo is started
  ansible.builtin.systemd:
    name: tempo.service
    state: started
    enabled: true

- name: Verify that Tempo URL is responding
  ansible.builtin.uri:
    url: "http://{{ tempo_http_listen_address }}:{{ tempo_http_listen_port }}/ready"
    method: GET
  register: tempo_verify_url_status_code
  retries: 5
  delay: 8
  until: tempo_verify_url_status_code.status == 200
  when:
    - not ansible_check_mode
