---
- name: DNF - Install Tempo from remote URL
  ansible.builtin.dnf:
    name: "{{ tempo_download_url_rpm }}"
    state: present
    disable_gpg_check: true
  notify: Restart tempo
  when: __current_deployed_version.stdout is not defined or tempo_version not in __current_deployed_version.stdout
