---
galaxy_info:
  role_name: promtail
  author: voidquark
  description: Manage Grafana Promtail Application
  license: "GPL-3.0-or-later"
  min_ansible_version: "2.10"
  platforms:
    - name: EL
      versions:
        - "9"
        - "8"
    - name: Fedora
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - promtail
    - grafana
    - logging
    - monitoring

dependencies: []
