---
- name: Deploy alloy
  hosts: all
  become: true
  roles:
    - role: grafana.grafana.alloy
  tasks:
    - name: Deploy alloy
      ansible.builtin.include_role:
        name: grafana.grafana.alloy
      vars:
        alloy_config: |
          prometheus.scrape "default" {
              targets = [{"__address__" = "127.0.0.1:12345"}]
              forward_to = [prometheus.remote_write.prom.receiver]
          }
          prometheus.remote_write "prom" {
            endpoint {
                url = "http://mimir:9009/api/v1/push"
            }
          }
