- name: Install OpenTelemetry Collector
  hosts: all
  become: true

  tasks:
    - name: Install OpenTelemetry Collector
      ansible.builtin.include_role:
        name: grafana.grafana.opentelemetry_collector
      vars:
        otel_collector_receivers:
          otlp:
            protocols:
              grpc:
                endpoint: 0.0.0.0:4317
              http:
                endpoint: 0.0.0.0:4318
        otel_collector_processors:
          batch:

        otel_collector_exporters:
          otlp:
            endpoint: otelcol:4317

        otel_collector_extensions:
          health_check:
          pprof:
          zpages:

        otel_collector_service:
          extensions: [health_check, pprof, zpages]
          pipelines:
            traces:
              receivers: [otlp]
              processors: [batch]
              exporters: [otlp]
            metrics:
              receivers: [otlp]
              processors: [batch]
              exporters: [otlp]
            logs:
              receivers: [otlp]
              processors: [batch]
              exporters: [otlp]
