---
galaxy_info:
  role_name: tempo
  author: Grafana
  description: Manage Grafana Tempo Application
  license: "GPL-3.0-or-later"
  min_ansible_version: "2.10"
  platforms:
    - name: EL
      versions:
        - "8"
        - "9"
    - name: Fedora
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - tempo
    - grafana
    - tracing
    - monitoring

dependencies: []
