galaxy_info:
  author: Ishan Jain
  description: Role to install and configure OpenTelemetry Collector
  license: "GPL-3.0-or-later"
  min_ansible_version: "2.11"
  platforms:
    - name: Fedora
      versions:
        - "all"
    - name: Debian
      versions:
        - "all"
    - name: Ubuntu
      versions:
        - "all"
    - name: EL
      versions:
        - "all"
  galaxy_tags:
    - grafana
    - observability
    - monitoring
    - opentelemetry
    - telemetry
    - collector
