---
galaxy_info:
  role_name: alloy
  author: Ishan Jain, voidquark
  description: Role to Install and Configure Grafana Alloy
  license: "GPL-3.0-or-later"
  min_ansible_version: "2.13"
  platforms:
    - name: EL
      versions:
        - "8"
        - "9"
    - name: Fedora
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
  galaxy_tags:
    - grafana
    - observability
    - monitoring
    - opentelemetry
    - telemetry
