---
# handlers file for loki
- name: Restart loki
  listen: "restart loki"
  ansible.builtin.systemd:
    daemon_reload: true
    name: loki.service
    state: restarted
    enabled: true
  when: not ansible_check_mode
