---
- name: "Run role"
  hosts: all
  any_errors_fatal: true
  roles:
    - grafana.grafana.grafana
  vars:
    grafana_ini:
      security:
        admin_user: admin
        admin_password: password
